### ISSUE TITLE
release fails on scala.js project

### ISSUE THREAD

**Issue by mrmechko** [sbt/sbt-release#121]
I get the following error when trying to use `sbt-release` (1.0.1) with a scalajs project.  I'm not sure if I'm missing a step or if there's another issue.

``` scala
java.io.IOException: Failed to deserialize info of /Users/mechko/.ivy2/cache/org.scala-js/scalajs-library_2.11/jars/scalajs-library_2.11-0.6.4.jar#scala/math/Ordering$Byte$.sjsir
    at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:135)
    at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:104)
    at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$2.apply(ScalaJSCoreLib.scala:33)
    at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$2.apply(ScalaJSCoreLib.scala:32)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.scalajs.jsenv.rhino.ScalaJSCoreLib.<init>(ScalaJSCoreLib.scala:32)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.loadClasspath(RhinoJSEnv.scala:307)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:149)
    at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:60)
    at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:64)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:453)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:438)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: This version (0.6.4) of Scala.js IR is not supported. Supported versions are: 0.6.0
    at org.scalajs.core.ir.InfoSerializers$Deserializer.readHeader(InfoSerializers.scala:149)
    at org.scalajs.core.ir.InfoSerializers$Deserializer.deserialize(InfoSerializers.scala:100)
    at org.scalajs.core.ir.InfoSerializers$.deserializeWithVersion(InfoSerializers.scala:35)
    at org.scalajs.core.ir.InfoSerializers$.deserialize(InfoSerializers.scala:31)
    at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:132)
    at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:104)
    at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$2.apply(ScalaJSCoreLib.scala:33)
    at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$2.apply(ScalaJSCoreLib.scala:32)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.scalajs.jsenv.rhino.ScalaJSCoreLib.<init>(ScalaJSCoreLib.scala:32)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.loadClasspath(RhinoJSEnv.scala:307)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:149)
    at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:60)
    at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:64)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:453)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$40.apply(ScalaJSPluginInternal.scala:438)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (stripsJS/test:loadedTestFrameworks) java.io.IOException: Failed to deserialize info of /Users/mechko/.ivy2/cache/org.scala-js/scalajs-library_2.11/jars/scalajs-library_2.11-0.6.4.jar#scala/math/Ordering$Byte$.sjsir
[error] Total time: 15 s, completed Jul 15, 2015 11:49:37 AM
```

**Comment by non** [comment]
Interestingly, I hit a different issue when trying to use sbt-release and sbt-scalajs together: https://github.com/InTheNow/sbt-scalajs/issues/19

**Comment by InTheNow** [comment]
The top issue is not sbt-release related - eg see https://groups.google.com/forum/#!topic/scala-js/a6jZNx6WMjs

"You're likely linking with 0.6.3 libraries compiled with 0.6.4. You have to use the sbt plugin of Scala.js 0.6.4."
