### ISSUE TITLE
Regression: with-defaults does not work for sbt-release 1.0.2

### ISSUE THREAD

**Issue by Atry** [sbt/sbt-release#142]
* The working version: https://travis-ci.org/ThoughtWorksInc/sbt-haxe/jobs/109414651
 * The failed version: https://travis-ci.org/ThoughtWorksInc/sbt-haxe/jobs/109413668
   
   ```
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/0.13.9/sbt-launch.jar
warn
"set javaHome in ThisBuild := Some(file("/usr/lib/jvm/java-7-openjdk-amd64"))"
info
"release with-defaults"
[info] Loading project definition from /home/travis/build/ThoughtWorksInc/sbt-haxe/project
[info] Updating {file:/home/travis/build/ThoughtWorksInc/sbt-haxe/project/}sbt-haxe-build...
[info] Resolving com.jsuereth#sbt-pgp;1.0.0 ...
[info] Resolving com.jsuereth#pgp-library_2.10;1.0.0 ...
[info] Resolving org.scala-lang#scala-library;2.10.5 ...
[info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
[info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
[info] Resolving net.databinder#dispatch-http_2.10;0.8.10 ...
[info] Resolving net.databinder#dispatch-core_2.10;0.8.10 ...
[info] Resolving org.apache.httpcomponents#httpclient;4.1.3 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.1.4 ...
[info] Resolving commons-logging#commons-logging;1.1.1 ...
[info] Resolving commons-codec#commons-codec;1.4 ...
[info] Resolving net.databinder#dispatch-futures_2.10;0.8.10 ...
[info] Resolving org.scala-lang#scala-actors;2.10.2 ...
[info] Resolving org.xerial.sbt#sbt-sonatype;0.5.0 ...
[info] Resolving org.apache.httpcomponents#httpclient;4.2.6 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.2.5 ...
[info] Resolving commons-codec#commons-codec;1.6 ...
[info] Resolving com.github.gseitz#sbt-release;1.0.2 ...
[info] Resolving org.scala-sbt#sbt;0.13.9 ...
[info] Resolving org.scala-sbt#main;0.13.9 ...
[info] Resolving org.scala-sbt#actions;0.13.9 ...
[info] Resolving org.scala-sbt#classpath;0.13.9 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.5 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.5 ...
[info] Resolving org.scala-sbt#interface;0.13.9 ...
[info] Resolving org.scala-sbt#io;0.13.9 ...
[info] Resolving org.scala-sbt#control;0.13.9 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.0-M1 ...
[info] Resolving org.scala-sbt#completion;0.13.9 ...
[info] Resolving org.scala-sbt#collections;0.13.9 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.9 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.9 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.9 ...
[info] Resolving org.scala-sbt#logging;0.13.9 ...
[info] Resolving org.scala-sbt#process;0.13.9 ...
[info] Resolving org.scala-sbt#relation;0.13.9 ...
[info] Resolving org.scala-sbt#compile;0.13.9 ...
[info] Resolving org.scala-sbt#classfile;0.13.9 ...
[info] Resolving org.scala-sbt#persist;0.13.9 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.9 ...
[info] Resolving org.scala-sbt#ivy;0.13.9 ...
[info] Resolving org.scala-sbt#cross;0.13.9 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93 ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.9 ...
[info] Resolving org.scala-sbt#task-system;0.13.9 ...
[info] Resolving org.scala-sbt#tasks;0.13.9 ...
[info] Resolving org.scala-sbt#tracking;0.13.9 ...
[info] Resolving org.scala-sbt#cache;0.13.9 ...
[info] Resolving org.scala-sbt#testing;0.13.9 ...
[info] Resolving org.scala-sbt#test-agent;0.13.9 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.9 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.9 ...
[info] Resolving org.scala-sbt#command;0.13.9 ...
[info] Resolving org.scala-sbt#logic;0.13.9 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.9 ...
[info] Resolving org.scala-lang#jline;2.10.5 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to sbt-haxe (in build file:/home/travis/build/ThoughtWorksInc/sbt-haxe/)
[info] Starting release process off commit: 384b2d77066ba95df303b0117a84281239141b89
[info] Checking remote [origin] ...
[info] Updating {file:/home/travis/build/ThoughtWorksInc/sbt-haxe/}sbt-haxe...
[info] Resolving org.apache.commons#commons-compress;1.2 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving org.scala-lang#scala-library;2.10.5 ...
[info] Resolving org.scala-sbt#sbt;0.13.9 ...
[info] Resolving org.scala-sbt#main;0.13.9 ...
[info] Resolving org.scala-sbt#actions;0.13.9 ...
[info] Resolving org.scala-sbt#classpath;0.13.9 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.5 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.5 ...
[info] Resolving org.scala-sbt#interface;0.13.9 ...
[info] Resolving org.scala-sbt#io;0.13.9 ...
[info] Resolving org.scala-sbt#control;0.13.9 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.0-M1 ...
[info] Resolving org.scala-sbt#completion;0.13.9 ...
[info] Resolving org.scala-sbt#collections;0.13.9 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.9 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.9 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.9 ...
[info] Resolving org.scala-sbt#logging;0.13.9 ...
[info] Resolving org.scala-sbt#process;0.13.9 ...
[info] Resolving org.scala-sbt#relation;0.13.9 ...
[info] Resolving org.scala-sbt#compile;0.13.9 ...
[info] Resolving org.scala-sbt#classfile;0.13.9 ...
[info] Resolving org.scala-sbt#persist;0.13.9 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.9 ...
[info] Resolving org.scala-sbt#ivy;0.13.9 ...
[info] Resolving org.scala-sbt#cross;0.13.9 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07abc51ec93 ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.9 ...
[info] Resolving org.scala-sbt#task-system;0.13.9 ...
[info] Resolving org.scala-sbt#tasks;0.13.9 ...
[info] Resolving org.scala-sbt#tracking;0.13.9 ...
[info] Resolving org.scala-sbt#cache;0.13.9 ...
[info] Resolving org.scala-sbt#testing;0.13.9 ...
[info] Resolving org.scala-sbt#test-agent;0.13.9 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.9 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.9 ...
[info] Resolving org.scala-sbt#command;0.13.9 ...
[info] Resolving org.scala-sbt#logic;0.13.9 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.9 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.9 ...
[info] Resolving org.scala-lang#jline;2.10.5 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
Release version [3.1.0] : java.lang.RuntimeException: No version provided!
	at scala.sys.package$.error(package.scala:27)
	at sbtrelease.ReleaseStateTransformations$.readVersion(ReleaseExtra.scala:272)
	at sbtrelease.ReleaseStateTransformations$$anonfun$inquireVersions$1.apply(ReleaseExtra.scala:67)
	at sbtrelease.ReleaseStateTransformations$$anonfun$inquireVersions$1.apply(ReleaseExtra.scala:56)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$2.sbtrelease$ReleasePlugin$autoImport$ReleaseKeys$$anonfun$$filterFailure$1(ReleasePlugin.scala:146)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$2$$anonfun$5$$anonfun$apply$3.apply(ReleasePlugin.scala:160)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$2$$anonfun$5$$anonfun$apply$3.apply(ReleasePlugin.scala:160)
	at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
	at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at scala.Function$$anonfun$chain$1.apply(Function.scala:24)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$2.apply(ReleasePlugin.scala:164)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$2.apply(ReleasePlugin.scala:121)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] No version provided!
[error] Use 'last' for the full log.
```

**Comment by xuwei-k** [comment]
Sorry, I just added some tests https://github.com/sbt/sbt-release/pull/145.
I believe this bug is already fixed in [current master 9879b2066dc](https://github.com/sbt/sbt-release/tree/9879b2066dc79a64a8).

**Comment by ssaifee** [comment]
I am facing the same issue.

**Comment by xuwei-k** [comment]
@jroper could you release next version(v1.0.3) and close this issue?

**Comment by jroper** [comment]
1.0.3 is released.

**Comment by xuwei-k** [comment]
> 1.0.3 is released.

Thanks! :smile:
