### ISSUE TITLE
Automate the sbt-release with the sub project

### ISSUE THREAD

**Issue by augustinchen-hbo** [sbt/sbt-release#211]
I have the following project structure. 

```
root
  |- subprojectA
  |- subprojectB
  |- project
  |- build.sbt
```

I want to automate the subproject release with Jenkins with the following command.
**sbt subprojectA/clean "release with-defaults"**

And I get the following error.

```
[info] Starting release process off commit: 61170aeb5cf9e4f4c58d3c37dedc41850b8
java.lang.RuntimeException: Repository for publishing is not specified.
        at scala.sys.package$.error(package.scala:27)
        at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1643)
        at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1643)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.Classpaths$.getPublishTo(Defaults.scala:1643)
        at sbtrelease.Compat$.checkPublishTo(Compat.scala:44)
        at sbtrelease.ReleaseStateTransformations$$anonfun$publishArtifacts$1.apply(ReleaseExtra.scala:269)
        at sbtrelease.ReleaseStateTransformations$$anonfun$publishArtifacts$1.apply(ReleaseExtra.scala:269)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$apply$4.apply(ReleasePlugin.scala:193)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$apply$4.apply(ReleasePlugin.scala:193)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.apply(ReleasePlugin.scala:193)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.apply(ReleasePlugin.scala:157)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.runCmd$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:187)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:61)
        at sbt.xMain.run(Main.scala:35)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] Repository for publishing is not specified.
[error] Use 'last' for the full log.
```

Please let me know the correct the command which can release a sub project in a non-interactive manner.  Thank you in advance.

**Comment by laughedelic** [comment]
Have you tried `subprojectA:release with-defaults`?

**Comment by augustinchen-hbo** [comment]
@laughedelic 
Thank you for your quick response.

But the command seems not working. I get command not found.
[root@ip dma-spark]# subprojectA:release with-defaults
-bash: subprojectA:release : command not found

When I add 'sbt' in front of the command, I get the following errors.
[root@ip dma-spark]# sbt subprojectA:release with-defaults
[info] Loading project definition from /root/spark/project
[info] Set current project to spark (in build file:/root/spark/)
[error] Not a valid key: release (similar: releaseVcs, releaseVcsSign, releaseProcess)
[error] subprojectA:release 
[error]  

I have to go into the sbt shell first, then release the project.
> [root@ip-10-69-1-164 dma-spark]# sbt
[info] Loading project definition from /root/spark/project
[info] Set current project to spark (in build file:/root/spark/)
> project  subprojectA
[info] Set current project to subprojectA (in build file:/root/dma-spark/)
> release with-defaults

 I'd like to release the sub project in BASH shell so that I can make it as a Jenkins job.

Any ideas please let me know. Thank you.

**Comment by laughedelic** [comment]
OK. So you have to pass all commands to sbt as a single command line argument, and if you want to run several commands, you have to prepend each with a semicolon:

```
sbt '; project  subprojectA ; release with-defaults'
```

This should do the same as what you do manually in your last example.

**Comment by laughedelic** [comment]
I just remembered that sbt treats arguments as a sequence of commands, so just in case what I wrote above doesn't work, you can also try

```
sbt 'project subprojectA' 'release with-defaults'
```

**Comment by ScalaWilliam** [comment]
`sbt subprojectA/release with-defaults`

**Comment by augustinchen-hbo** [comment]
Thank you @laughedelic , both your ways work.

Sorry, @ScalaWilliam 

I get the following errors with the command. Anyway, thank you for your help.
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: release (similar: releaseVcs, releaseVcsSign, releaseProcess)
[error] subprojectA/release with-defaults
