### ISSUE TITLE
Release fails because of modified version file

### ISSUE THREAD

**Issue by MichaelJAllen** [sbt/sbt-release#212]
Hi!

I'm using `sbt-release` version `1.0.6` with `sbt` version `1.0.2` and I'm finding that the basic release process is failing. (It used to work not too long ago; I'm just using the default release sequence.) I have created a minimal [GitHub project](https://github.com/MichaelJAllen/sbt-release-fail) that illustrates the problem. To reproduce, just run the following commands:

```
git clone https://github.com/MichaelJAllen/sbt-release-fail
cd sbt-release-fail
sbt release
```

When prompted, keep the release version as `1.0.0` and the next version as `1.0.1-SNAPSHOT`. You should see output like the following:

```
"C:\Users\someuser\.sbt\preloaded\org.scala-sbt\sbt\"1.0.0"\jars\sbt.jar"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from C:\Users\someuser\.sbt\1.0\plugins
[info] Loading settings from Release.sbt ...
[info] Loading project definition from C:\Users\someuser\src\sbt-release-fail\project
[info] Updating {file:/C:/Users/someuser/src/sbt-release-fail/project/}sbt-release-fail-build...
[info] Done updating.
[info] Loading settings from build.sbt,Version.sbt ...
[info] Set current project to sbt-release failure (in build file:/C:/Users/someuser/src/sbt-release-fail/)
[info] Starting release process off commit: 0fb1dc7755c786dc5f12364e48eb395a3f66c3fb
[info] Checking remote [origin] ...
[info] Updating {file:/C:/Users/someuser/src/sbt-release-fail/}sbt-release-fail...
[info] Done updating.
Release version [1.0.0] :
Next version [1.0.1-SNAPSHOT] :
[success] Total time: 0 s, completed Oct 4, 2017 9:49:31 AM
[info] Updating {file:/C:/Users/someuser/src/sbt-release-fail/}sbt-release-fail...
[info] Done updating.
[info] Compiling 1 Scala source to C:\Users\someuser\src\sbt-release-fail\target\scala-2.12\classes ...
[info] Done compiling.
[info] Run completed in 25 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 1 s, completed Oct 4, 2017 9:49:33 AM
[info] Setting version to '1.0.0'.
[info] Reapplying settings...
[info] Set current project to sbt-release failure (in build file:/C:/Users/someuser/src/sbt-release-fail/)
[info] fatal: pathspec 'Version file [Version.sbt] is outside of this VCS repository with base directory [C:\Users\someuser\src\sbt-release-fail]!' did not match any files
[error] java.lang.RuntimeException: Nonzero exit value: 128
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:134)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:105)
[error]         at sbtrelease.ReleaseStateTransformations$.$anonfun$commitVersion$1(ReleaseExtra.scala:151)
[error]         at sbtrelease.ReleaseStateTransformations$.$anonfun$commitReleaseVersionAction$1(ReleaseExtra.scala:135)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$7(ReleasePlugin.scala:190)
[error]         at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:86)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:194)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error]         at sbt.State$$anon$1.process(State.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:105)
[error]         at sbt.MainLoop$.run(MainLoop.scala:98)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error]         at sbt.StandardMain$.runManaged(Main.scala:104)
[error]         at sbt.xMain.run(Main.scala:71)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Nonzero exit value: 128
[error] Use 'last' for the full log.
```

What seems to be happening is that the release process has (correctly) updated the `Version.sbt` file so that it's contents reflect the version to be released, but then complains that this file has been modified and not committed. Instead, it should commit the updated version and tag it before attempting to publish the resulting artifact, but it doesn't seem to get that far...

Am I missing something?

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-release/issues/212

workaround

```diff
- releaseVersionFile := file("Version.sbt")
+ releaseVersionFile := baseDirectory.value / "Version.sbt"
```

**Comment by xuwei-k** [comment]
https://github.com/sbt/io/issues/94
