### ISSUE TITLE
Failed to retrieve data from `/staging/profiles/`

### ISSUE THREAD

**Issue by atais** [sbt/sbt-release#223]
I have managed to make a new release but the build failed in the meantime with an error:

```
[info] Dropping staging repository [comgithubatais-1010] status:released, profile:com.github.atais(731ffb308adb05) description: Implicitly created (auto staging).
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
[warn] Received 500 error: HTTP/1.1 500 Server Error. Retrying...
java.io.IOException: Failed to retrieve data from /staging/profiles/731ffb308adb05/drop
        at xerial.sbt.Sonatype$NexusRESTService.Post(Sonatype.scala:605)
        at xerial.sbt.Sonatype$NexusRESTService.dropStage(Sonatype.scala:781)
        at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:852)
        at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$27$$anonfun$apply$18.apply(Sonatype.scala:279)
        at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$27$$anonfun$apply$18.apply(Sonatype.scala:278)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$27.apply(Sonatype.scala:278)
        at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$27.apply(Sonatype.scala:275)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at $7bba9360fd1d173ff1fb$$anonfun$main$13$$anonfun$2.apply(build.sbt:49)
        at $7bba9360fd1d173ff1fb$$anonfun$main$13$$anonfun$2.apply(build.sbt:49)
        at sbtrelease.ReleaseStateTransformations$$anonfun$runCrossBuild$1$$anonfun$17.apply(ReleaseExtra.scala:319)
        at sbtrelease.ReleaseStateTransformations$$anonfun$runCrossBuild$1$$anonfun$17.apply(ReleaseExtra.scala:318)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at sbtrelease.ReleaseStateTransformations$$anonfun$runCrossBuild$1.apply(ReleaseExtra.scala:318)
        at sbtrelease.ReleaseStateTransformations$$anonfun$runCrossBuild$1.apply(ReleaseExtra.scala:313)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.sbtrelease$ReleasePlugin$autoImport$ReleaseKeys$$anonfun$$filterFailure$1(ReleasePlugin.scala:175)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$9$$anonfun$apply$3.apply(ReleasePlugin.scala:192)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$9$$anonfun$apply$3.apply(ReleasePlugin.scala:192)
        at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
        at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at scala.Function$$anonfun$chain$1.apply(Function.scala:24)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.apply(ReleasePlugin.scala:199)
        at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5.apply(ReleasePlugin.scala:156)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.doX$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:190)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:109)
        at sbt.xMain.run(Main.scala:38)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)

```

all configs are available:
https://github.com/atais/fixed-length

so if it was my fault I would be glad for any recommendation.

**Comment by xuwei-k** [comment]
I think this is not sbt-release issue

**Comment by atais** [comment]
I could try to make a follow up on next release, but I do not not know when it is coming. :(

What info would be beneficial for you?

**Comment by dwijnand** [comment]
the failure is in running `closeAndPromote` in sbt-sonatype, via sbt-release.

so it's an issue for https://github.com/xerial/sbt-sonatype, rather than here.
