### ISSUE TITLE
NoSuchMethodError in sbt.internal.KeyIndex in 1.0.6

### ISSUE THREAD

**Issue by wsargent** [sbt/sbt-release#237]
Using 

addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.6")

with sbt 1.2.3

```
[1.6.x] root: last
[debug] > Exec(release, Some(5323a111-5f37-49d8-a0a5-b7e6724edc14), Some(CommandSource(console0)))
[info] Starting release process off commit: 1ca232857618f28bade8fba728a54ed8493cfa3d
[debug] Running task... Cancel: Null, check cycles: false, forcegc: true
[info] Checking remote [origin] ...
[info] Setting scala version to 2.12.7
[error] java.lang.NoSuchMethodError: sbt.internal.KeyIndex$.apply(Lscala/collection/Iterable;Lscala/collection/immutable/Map;)Lsbt/internal/ExtendableKeyIndex;
[error] 	at sbtrelease.Load$.structureIndex(Load.scala:58)
[error] 	at sbtrelease.Load$.reapply(Load.scala:20)
[error] 	at sbtrelease.ReleaseStateTransformations$.switchScalaVersion(ReleaseExtra.scala:309)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$runCrossBuild$2(ReleaseExtra.scala:319)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$runCrossBuild$1(ReleaseExtra.scala:318)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:176)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$6(ReleasePlugin.scala:189)
[error] 	at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:86)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:151)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:151)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:194)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: sbt.internal.KeyIndex$.apply(Lscala/collection/Iterable;Lscala/collection/immutable/Map;)Lsbt/internal/ExtendableKeyIndex;
[error] Use 'last' for the full log.
[debug] > Exec(shell, None, None)
[debug] Running task... Cancel: Null, check cycles: false, forcegc: true
```

**Comment by wsargent** [comment]
Updating to 1.0.9 and removing all target folders resolved the issue.
