### ISSUE TITLE
Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact

### ISSUE THREAD

**Issue by pathikrit** [sbt/sbt-release#246]
[build.sbt](https://github.com/pathikrit/better-files/blob/800d63d31582b4119074e0593d257992c1b3cbee/build.sbt)

```
> sbt +release
[info] Loading settings for project global-plugins from idea.sbt,metals.sbt ...
[info] Loading global plugins from /Users/pbhowmick/.sbt/1.0/plugins
[info] Loading settings for project better-files-build from plugins.sbt ...
[info] Loading project definition from /Users/pbhowmick/workspace/better-files/project
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Forcing Scala version to 2.11.12 on all projects.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Updating ...
[info] Done updating.
Release version [3.7.1] :
Next version [3.7.2-SNAPSHOT] :
[info] Setting version to '3.7.1'.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
Tag [v3.7.1] exists! Overwrite, keep or abort or enter a new tag (o/k/a)? [a] o
[warn] Overwriting a tag can cause problems if others have already seen the tag (see `git help tag`)!
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Wrote /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.1.pom
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1.jar.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1.pom.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-sources.jar.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-sources.jar
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1.jar
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1.pom
[success] Total time: 6 s, completed Mar 1, 2019 9:41:19 AM
[info] Setting version to '3.7.2-SNAPSHOT'.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.github.pathikrit
[info] Reading staging repository profiles...
[info] Repository comgithubpathikrit-1057 is already closed
[info] Activity open started:2019-02-25T15:58:47.620Z, stopped:2019-02-25T16:00:03.384Z
[info] repositoryCreated: id:comgithubpathikrit-1057, user:pathikrit, ip:158.106.220.50
[info] Activity close started:2019-02-25T16:07:34.805Z, stopped:2019-02-25T16:16:15.069Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: no-traversal-paths-in-archive-file
[info]     Passed: no-traversal-paths-in-archive-file
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: profile-target-matching-staging
[info]     Passed: profile-target-matching-staging
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]     Passed: id:5e9e8e6f8d20a3
[info]      email: to:pathikritbhowmick@msn.com
[info] repositoryClosed: id:comgithubpathikrit-1057
[info] Closed successfully
[info] Reading staging profiles...
[info] Promoting staging repository [comgithubpathikrit-1057] status:closed, profile:com.github.pathikrit(3ce6558c41fb47) description: Implicitly created (auto staging).
[info] Activity release started:2019-03-01T14:41:26.318Z, stopped:
[info]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy
[info]   Evaluate: RepositoryWritePolicy
[info]     Passed: RepositoryWritePolicy
[info]     Passed: id:nx-internal-ruleset
[info]  copyItems: source:comgithubpathikrit-1057, target:releases
[info]      email: to:pathikritbhowmick@msn.com
[info] repositoryReleased: id:comgithubpathikrit-1057, target:releases
[info] Promoted successfully
[info] Dropping staging repository [comgithubpathikrit-1057] status:released, profile:com.github.pathikrit(3ce6558c41fb47) description: Implicitly created (auto staging).
[info] Dropped successfully: comgithubpathikrit-1057
[info] Closing staging repository [comgithubpathikrit-1058] status:open, profile:com.github.pathikrit(3ce6558c41fb47) description: Implicitly created (auto staging).
[info] Activity open started:2019-03-01T14:36:10.166Z, stopped:2019-03-01T14:36:16.304Z
[info] repositoryCreated: id:comgithubpathikrit-1058, user:pathikrit, ip:158.106.220.50
[info] Activity close started:2019-03-01T14:41:40.287Z, stopped:
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: profile-target-matching-staging
[info]     Passed: profile-target-matching-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: no-traversal-paths-in-archive-file
[info]     Passed: no-traversal-paths-in-archive-file
[info]     Passed: id:5e9e8e6f8d20a3
[info]      email: to:pathikritbhowmick@msn.com
[info] repositoryClosed: id:comgithubpathikrit-1058
[info] Closed successfully
[info] Promoting staging repository [comgithubpathikrit-1058] status:closed, profile:com.github.pathikrit(3ce6558c41fb47) description: Implicitly created (auto staging).
[info] Activity release started:2019-03-01T14:42:23.165Z, stopped:2019-03-01T14:42:28.168Z
[info]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy
[info]   Evaluate: RepositoryWritePolicy
[info]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar'
[info]     Failed: id:nx-internal-ruleset, failureCount:1
[info] repositoryReleaseFailed: id:comgithubpathikrit-1058, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[error] Failed to promote the repository
[error] Activity release started:2019-03-01T14:42:23.165Z, stopped:2019-03-01T14:42:28.168Z
[error]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar'
[error] java.lang.Exception: Failed to promote the repository
[error]         at xerial.sbt.Sonatype$NexusRESTService.promoteStage(Sonatype.scala:827)
[error]         at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:855)
[error]         at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeReleaseAll$2(Sonatype.scala:279)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:294)
[error]         at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeReleaseAll$1(Sonatype.scala:278)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbtrelease.ReleasePlugin$autoImport$.$anonfun$releaseStepCommand$2(ReleasePlugin.scala:94)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:177)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$9(ReleasePlugin.scala:195)
[error]         at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:85)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:201)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.Exception: Failed to promote the repository
[error] Use 'last' for the full log.
```

**Comment by pathikrit** [comment]
I tried skipping the `3.7.1` to `3.7.2` and I still get same error:

```
> sbt +release
[info] Loading settings for project global-plugins from idea.sbt,metals.sbt ...
[info] Loading global plugins from /Users/pbhowmick/.sbt/1.0/plugins
[info] Loading settings for project better-files-build from plugins.sbt ...
[info] Loading project definition from /Users/pbhowmick/workspace/better-files/project
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Forcing Scala version to 2.11.12 on all projects.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
Release version [3.7.1] : 3.7.2
Next version [3.7.3-SNAPSHOT] :
[info] Setting version to '3.7.2'.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Updating core...
[info] Packaging /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.2-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.2.pom
[info] Done updating.
[info] Main Scala API documentation to /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/api...
[info] Packaging /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.2.jar ...
[info] Done packaging.
model contains 72 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.7.2-javadoc.jar ...
[info] Done packaging.
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[error] gpg: using "0x66aa02ec8aa60db9" as default secret key for signing
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2.jar.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2.pom.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2-javadoc.jar
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2-sources.jar.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2-javadoc.jar.asc
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2-sources.jar
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2.jar
[info]  published better-files_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/pathikrit/better-files_2.11/3.7.2/better-files_2.11-3.7.2.pom
[success] Total time: 12 s, completed Mar 1, 2019 9:50:03 AM
[info] Setting version to '3.7.3-SNAPSHOT'.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.github.pathikrit
[info] Reading staging repository profiles...
[info] Repository comgithubpathikrit-1058 is already closed
[info] Activity open started:2019-03-01T14:36:10.166Z, stopped:2019-03-01T14:36:16.304Z
[info] repositoryCreated: id:comgithubpathikrit-1058, user:pathikrit, ip:158.106.220.50
[info] Activity close started:2019-03-01T14:41:40.287Z, stopped:2019-03-01T14:42:11.304Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: profile-target-matching-staging
[info]     Passed: profile-target-matching-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: javadoc-staging
[info]     Passed: javadoc-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: sources-staging
[info]     Passed: sources-staging
[info]   Evaluate: no-traversal-paths-in-archive-file
[info]     Passed: no-traversal-paths-in-archive-file
[info]     Passed: id:5e9e8e6f8d20a3
[info]      email: to:pathikritbhowmick@msn.com
[info] repositoryClosed: id:comgithubpathikrit-1058
[info] Activity release started:2019-03-01T14:42:23.165Z, stopped:2019-03-01T14:42:28.168Z
[info]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy
[info]   Evaluate: RepositoryWritePolicy
[info]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar'
[info]     Failed: id:nx-internal-ruleset, failureCount:1
[info] repositoryReleaseFailed: id:comgithubpathikrit-1058, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity release started:2019-03-01T14:48:27.046Z, stopped:2019-03-01T14:48:32.068Z
[info]   Evaluate: id:nx-internal-ruleset, rule:RepositoryWritePolicy
[info]   Evaluate: RepositoryWritePolicy
[info]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar'
[info]     Failed: id:nx-internal-ruleset, failureCount:1
[info] repositoryReleaseFailed: id:comgithubpathikrit-1058, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Closed successfully
[info] Reading staging profiles...
[info] Promoting staging repository [comgithubpathikrit-1058] status:closed, profile:com.github.pathikrit(3ce6558c41fb47) description: Implicitly created (auto staging).
[error] Failed to promote the repository
[error] Activity release started:2019-03-01T14:48:27.046Z, stopped:2019-03-01T14:48:32.068Z
[error]     Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/github/pathikrit/better-files_2.11/3.7.1/better-files_2.11-3.7.1-javadoc.jar'
[error] java.lang.Exception: Failed to promote the repository
[error]         at xerial.sbt.Sonatype$NexusRESTService.promoteStage(Sonatype.scala:827)
[error]         at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:855)
[error]         at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeReleaseAll$2(Sonatype.scala:279)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:294)
[error]         at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeReleaseAll$1(Sonatype.scala:278)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbtrelease.ReleasePlugin$autoImport$.$anonfun$releaseStepCommand$2(ReleasePlugin.scala:94)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.filterFailure$1(ReleasePlugin.scala:177)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$9(ReleasePlugin.scala:195)
[error]         at scala.Function$.$anonfun$chain$2(Function.scala:24)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:85)
[error]         at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
[error]         at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
[error]         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error]         at scala.Function$.$anonfun$chain$1(Function.scala:24)
[error]         at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$2(ReleasePlugin.scala:201)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.Exception: Failed to promote the repository
[error] Use 'last' for the full log.
```
