### ISSUE TITLE
Unexpected error when reading staging repository profiles

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt-release#292]
```
2021-04-28 14:26:01.267+0200  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:108)
java.io.IOException: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in scala.package
	at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:124)
	at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:66)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:47)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.unpickleClass(JavaMirrors.scala:660)
	at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.$anonfun$complete$2(SymbolLoaders.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:332)
	at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.complete(SymbolLoaders.scala:34)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1551)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$13.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:221)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$13.info(SynchronizedSymbols.scala:221)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:355)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:410)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.$anonfun$complete$3(SymbolLoaders.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:332)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.complete(SymbolLoaders.scala:80)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1551)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:209)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.info(SynchronizedSymbols.scala:209)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2280)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.init(FindMembers.scala:36)
	at scala.reflect.internal.tpe.FindMembers$FindMember.init(FindMembers.scala:257)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1042)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1041)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1046)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:672)
	at scala.reflect.internal.Types$Type.member(Types.scala:636)
	at scala.reflect.internal.Mirrors$RootsBase.staticPackage(Mirrors.scala:55)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.staticPackage(JavaMirrors.scala:97)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$init$1(Mirrors.scala:268)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:265)
	at scala.reflect.runtime.JavaMirrors.createMirror(JavaMirrors.scala:47)
	at scala.reflect.runtime.JavaMirrors.$anonfun$runtimeMirror$1(JavaMirrors.scala:64)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror(JavaMirrors.scala:62)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror$(JavaMirrors.scala:61)
	at scala.reflect.runtime.JavaUniverse.runtimeMirror(JavaUniverse.scala:30)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.mirrorDefining(JavaMirrors.scala:607)
	at scala.reflect.runtime.SymbolLoaders$PackageScope.$anonfun$lookupEntry$1(SymbolLoaders.scala:148)
	at scala.reflect.runtime.SymbolLoaders$PackageScope.syncLockSynchronized(SymbolLoaders.scala:133)
	at scala.reflect.runtime.SymbolLoaders$PackageScope.lookupEntry(SymbolLoaders.scala:135)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.walkBaseClasses(FindMembers.scala:110)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.searchConcreteThenDeferred(FindMembers.scala:75)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.apply(FindMembers.scala:55)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1043)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1041)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1046)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:672)
	at scala.reflect.internal.Types$Type.member(Types.scala:636)
	at scala.reflect.internal.Types$Type.packageObject(Types.scala:648)
	at scala.reflect.internal.Symbols$Symbol.packageObject(Symbols.scala:859)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:404)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.$anonfun$complete$3(SymbolLoaders.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:332)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.complete(SymbolLoaders.scala:80)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1551)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:209)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.info(SynchronizedSymbols.scala:209)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2280)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.init(FindMembers.scala:36)
	at scala.reflect.internal.tpe.FindMembers$FindMember.init(FindMembers.scala:257)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1042)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1041)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1046)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:672)
	at scala.reflect.internal.Types$Type.member(Types.scala:636)
	at scala.reflect.internal.Mirrors$RootsBase.staticPackage(Mirrors.scala:55)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.staticPackage(JavaMirrors.scala:97)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$init$1(Mirrors.scala:268)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:265)
	at scala.reflect.runtime.JavaMirrors.createMirror(JavaMirrors.scala:47)
	at scala.reflect.runtime.JavaMirrors.$anonfun$runtimeMirror$1(JavaMirrors.scala:64)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror(JavaMirrors.scala:62)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror$(JavaMirrors.scala:61)
	at scala.reflect.runtime.JavaUniverse.runtimeMirror(JavaUniverse.scala:30)
	at scala.reflect.runtime.JavaUniverse.runtimeMirror(JavaUniverse.scala:30)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.$anonfun$mirror$1(ReflectSurfaceFactory.scala:167)
	at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
	at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
	at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.mirror(ReflectSurfaceFactory.scala:167)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.wvlet$airframe$surface$reflect$ReflectSurfaceFactory$$resolveClass(ReflectSurfaceFactory.scala:173)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.$anonfun$methodParametersOf$1(ReflectSurfaceFactory.scala:525)
	at scala.collection.immutable.List.map(List.scala:293)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.methodParametersOf(ReflectSurfaceFactory.scala:524)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.apply(ReflectSurfaceFactory.scala:558)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.apply(ReflectSurfaceFactory.scala:551)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.applyOrElse(ReflectSurfaceFactory.scala:551)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:546)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:546)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:458)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:458)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:437)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:437)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:431)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:431)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:426)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:426)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:421)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:421)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:354)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:354)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:381)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:381)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:400)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:400)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:395)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:395)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.surfaceOf(ReflectSurfaceFactory.scala:326)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$genericSurfaceFactory$1.$anonfun$applyOrElse$3(ReflectSurfaceFactory.scala:591)
	at scala.collection.immutable.List.map(List.scala:293)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$genericSurfaceFactory$1.applyOrElse(ReflectSurfaceFactory.scala:591)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$genericSurfaceFactory$1.applyOrElse(ReflectSurfaceFactory.scala:589)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.applyOrElse(ReflectSurfaceFactory.scala:551)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:546)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:546)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:458)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:458)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:437)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:437)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:431)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:431)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:426)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:426)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:421)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:421)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:354)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:354)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:381)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:381)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:400)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:400)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:395)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:395)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.surfaceOf(ReflectSurfaceFactory.scala:326)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.$anonfun$apply$1(ReflectSurfaceFactory.scala:134)
	at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
	at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
	at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.apply(ReflectSurfaceFactory.scala:134)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.ofType(ReflectSurfaceFactory.scala:50)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.localSurfaceOf(ReflectSurfaceFactory.scala:85)
	at wvlet.airframe.surface.SurfaceFactory$.localSurfaceOf(SurfaceFactory.scala:24)
	at wvlet.airframe.codec.MessageCodecFactory.of(MessageCodecFactory.scala:72)
	at xerial.sbt.sonatype.SonatypeService.withCache(SonatypeService.scala:122)
	at xerial.sbt.sonatype.SonatypeService.stagingProfiles(SonatypeService.scala:138)
	at xerial.sbt.sonatype.SonatypeService.currentProfile$lzycompute(SonatypeService.scala:143)
	at xerial.sbt.sonatype.SonatypeService.currentProfile(SonatypeService.scala:142)
	at xerial.sbt.sonatype.SonatypeService.createStage(SonatypeService.scala:154)
	at xerial.sbt.Sonatype$.$anonfun$prepare$3(Sonatype.scala:163)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-04-28 14:26:02.554+0200  info [SonatypeClient] Reading staging profiles...  - (SonatypeClient.scala:120)
2021-04-28 14:26:03.939+0200  warn [ObjectCodec] No factory is found for Map[String,Seq[StagingRepositoryProfile]]  - (ObjectCodec.scala:227)
2021-04-28 14:26:03.941+0200 error [Sonatype] 
java.lang.NullPointerException
	at xerial.sbt.sonatype.SonatypeClient.stagingRepositoryProfiles(SonatypeClient.scala:111)
	at xerial.sbt.sonatype.SonatypeService.stagingRepositoryProfiles(SonatypeService.scala:113)
	at xerial.sbt.sonatype.SonatypeService.findStagingRepositoryProfilesWithKey(SonatypeService.scala:107)
	at xerial.sbt.sonatype.SonatypeService.dropIfExistsByKey(SonatypeService.scala:94)
	at xerial.sbt.Sonatype$.$anonfun$prepare$2(Sonatype.scala:161)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)  - (Sonatype.scala:428)
```

**Comment by plokhotnyuk** [comment]
Moved to https://github.com/xerial/sbt-sonatype/issues/230
