### ISSUE TITLE
could not release new version with sbt-ci-release

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-release#394]
https://github.com/sbt/sbt-release/actions/runs/7342767265/job/19992427392

🤔 

```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --batch --yes --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/sbt-release/sbt-release/target/scala-2.12/sbt-1.0/sbt-release_2.12_1.0-1.2.0-javadoc.jar.asc /home/runner/work/sbt-release/sbt-release/target/scala-2.12/sbt-1.0/sbt-release_2.12_1.0-1.2.0-javadoc.jar'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.jsuereth.sbtpgp.CommandLineGpgSigner.sign(PgpSigner.scala:82)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:151)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:146)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:2[83](https://github.com/sbt/sbt-release/actions/runs/7342767265/job/19992427392#step:4:84))
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (signedArtifacts) Failure running 'gpg --batch --yes --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/sbt-release/sbt-release/target/scala-2.12/sbt-1.0/sbt-release_2.12_1.0-1.2.0-javadoc.jar.asc /home/runner/work/sbt-release/sbt-release/target/scala-2.12/sbt-1.0/sbt-release_2.12_1.0-1.2.0-javadoc.jar'.  Exit code: 2
```

**Comment by xuwei-k** [comment]
maybe expired key?

**Comment by eed3si9n** [comment]
As far as I know the key expires on 2025-02-03.

**Comment by eed3si9n** [comment]
Uploading the GPG private key again fixed the issue - https://github.com/sbt/sbt-release/actions/runs/7342983166/job/20013364809
